# Generated by Django 2.2.7 on 2019-11-16 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
        migrations.AlterModelTable(
            name='account_type',
            table='Account_Type',
        ),
        migrations.AlterModelTable(
            name='bank',
            table='Bank',
        ),
    ]
