# Generated by Django 2.2.7 on 2019-11-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191115_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='account_type',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
