# Generated by Django 2.2.7 on 2019-11-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191116_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='income',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='income',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
