# Generated by Django 2.2.7 on 2019-11-16 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191116_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='income',
        ),
        migrations.RemoveField(
            model_name='account',
            name='rate',
        ),
    ]
