# Generated by Django 2.2.7 on 2019-11-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191116_0120'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='account_type',
            table='account_type',
        ),
        migrations.AlterModelTable(
            name='bank',
            table='bank',
        ),
    ]
