# Generated by Django 2.2.7 on 2019-11-17 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191116_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account'},
        ),
        migrations.AlterModelOptions(
            name='account_type',
            options={'verbose_name': 'Account Type'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Bank'},
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Bank'),
            preserve_default=False,
        ),
    ]
