# Generated by Django 2.2.7 on 2019-11-16 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='Expense',
        ),
        migrations.AlterModelTable(
            name='expense_type',
            table='Expense_Type',
        ),
    ]
