# Generated by Django 2.2.7 on 2019-11-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20191116_0025'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expense',
            table='expense',
        ),
        migrations.AlterModelTable(
            name='expense_type',
            table='expense_type',
        ),
    ]
