# Generated by Django 2.2.7 on 2019-11-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_auto_20191116_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Expense'},
        ),
        migrations.AlterModelOptions(
            name='expense_type',
            options={'verbose_name': 'Expense Type'},
        ),
    ]
